require 'fudge/exceptions/base'
require 'fudge/exceptions/task_not_found'
require 'fudge/exceptions/build_failed'
require 'fudge/exceptions/cli/command_not_given'
require 'fudge/exceptions/cli/command_not_found'
